version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
        restart: always
        ports:
              - "9200:9200"
              - "9300:9300"
        networks:
              - elk
        volumes:
              - elastic:/usr/share/elasticsearch
        environment:
              discovery.type: single-node
    kibana:    
        image: docker.elastic.co/kibana/kibana:7.13.1
        restart: always
        ports:
              - "5601:5601"
        networks:
              - elk
        volumes:
              - kibana:/usr/share/kibana
        depends_on:
              - elasticsearch
volumes:
    elastic:
    kibana:
networks:
    elk:  
